# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: frading
  password: password

development:
  <<: *default
  database: guillaumefradin_dev

test:
  <<: *default
  database: guillaumefradin_test

production:
  <<: *default
  database: guillaumefradin_prod

